# Generated by Django 5.2.17 on 2026-09-13 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(choices=[('highschool', 'High School'), ('bachelor', 'Bachelor Degree (S1)'), ('certification', 'Certification/Course')], max_length=20)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Front-End Development'), ('backend', 'Back-End Development'), ('design', 'UI/UX Design'), ('softskill', 'Soft Skill')], default='softskill', max_length=20)),
                ('description', models.TextField()),
                ('proficiency_level', models.IntegerField(help_text='Tingkat kemahiran (1-100)')),
            ],
        ),
    ]
